version: "3.8"
services:
  psql: 
    build: ./pgsql
    ports:
      - 5432:5432
    command: bash -c "sleep 20; service ssh start;"
  apache:
    depends_on:
      - psql
    build: ./webserver
    ports:
      - 8080:80
      - 12345:22
    volumes:
      - ./webserver/htdocs:/var/www/html
      - ./webserver/private_request:/var/private_request
    # command: bash -c "sleep 4; sshpass -p password ssh root@psql -o StrictHostKeyChecking=accept-new '/setup/templateBuilder.sh'; apt-get remove -y sshpass; apt remove -y openssh-client"