version: "3.8"
services:
  psql: 
    build: ./pgsql
    ports:
      - 5432:5432
    #start psql and run templateBuilder.sh (crashes webserver tho)
    # command: ["/bin/bash","-c","su -l postgres -c '/usr/lib/postgresql/15/bin/initdb -D /var/lib/postgresql/data'; su -l postgres -c '/usr/lib/postgresql/15/bin/pg_ctl -D /var/lib/postgresql/data -l logfile start'; sh /setup/templateBuilder.sh && tail -F /dev/null"]    
  
  apache:
    build: ./webserver
    ports:
      - 8080:80
    volumes:
      - ./webserver/htdocs:/var/www/html
      - ./webserver/private_request:/var/private_request