version: "1"
services:
  apachefiddle:
    image: php:8.0-apache
    ports:
      - 8080:80
      #  docker run -dit --rm 
        # --name apachefiddle 
        # -p 8080:80 
        # -v "G:\actual\vsc\htmlfiddle\webserver/htdocs:/var/www/html" 
        # -v "G:\actual\vsc\htmlfiddle\webserver/private_request:/var/private_request" 
        # aphpchefiddle
  psqlfiddle:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_INITDB_ARGS=--locale-provider=icu --icu-locale=en-US