version: '3.8'
services:
  psql: 
    build: ./pgsql
    profiles:
      -  donotstart
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER:        'postgres'
      POSTGRES_PASSWORD:    'password'
      POSTGRES_DB:          'chatdb'
      POSTGRES_INITDB_ARGS: '--locale-provider=icu --icu-locale=en-US'
    volumes:
      - ./pgsql/postgres-data:/var/lib/postgresql/data
    networks:
      backend:
        aliases:
          - pgsql-db
  
  apache:
    build: ./webserver
    ports:
      - 8080:80
    volumes:
      - ./webserver/htdocs:/var/www/html
      - ./webserver/private_request:/var/private_request
    networks:
      backend:
        aliases:
          - app

  adminer:
    image: adminer:4.8.1-standalone
    profiles:
      -  donotstart
    restart: always
    ports:
      - 5433:8080 
    networks:
      backend:
        aliases:
          - adminer
  
networks:
  backend:
    name: backend-network