####################
### ref dockerfile
####################

FROM georgebb/htmlfiddlepgsql:1

ENV LANG en_US.utf8

ENV POSTGRES_PASSWORD "password"
ENV POSTGRES_INITDB_ARGS "--locale-provider=icu --icu-locale=en-US"

RUN localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
WORKDIR /
RUN rmdir ./temp

EXPOSE 5432